# Generated by Django 3.1.7 on 2021-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20210330_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default='test@test.ru', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='test_user', max_length=100),
            preserve_default=False,
        ),
    ]
