# Generated by Django 3.1.7 on 2021-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20210330_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'not done'), (1, 'not done. edited by admin'), (10, 'ok'), (11, 'ok. edited by admin')], default=0),
        ),
    ]
