# Generated by Django 3.1.7 on 2021-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
